### ISSUE TITLE
bandera-azul inconsistency between menu and page results

### ISSUE THREAD

**Issue by daniheras** [jmlweb/playasmurcia#2]
Beaches under _bandera-azul_ feature are not showed up but the menu item shows that there should be 25 

![image](https://github.com/jmlweb/playasmurcia/assets/24685447/d4d59d8c-000f-4cae-a08a-93dcb2e6824f)
![image](https://github.com/jmlweb/playasmurcia/assets/24685447/e8bd7344-592c-49bb-9621-12fd2713438a)

**Comment by jmlweb** [comment]
F***ing done
